export const API_URL = '/transactionsData.json';
export const REWARD_POINTS_HEADING = 'Rewards Points';
export const MONTHLY_REWARDS_HEADING = 'Monthly Rewards'
export const CUSTOMER_ID = 'Customer ID'
export const NAME = 'Name'
export const MONTH = 'Month'
export const YEAR = 'Year'
export const TRANSACTIONS_HEADING = 'Transactions'
export const TRANSACTIONS_ID = 'Transaction ID'
export const PRODUCT = 'Product'
export const PURCHASE_DATE = 'Purchase Date'
export const PRICE = 'Price'
export const TOTAL_REWARDS_HEADING = 'Total Rewards'
export const TRANSACTIONS_FETCHED = 'Transactions fetched successfully:- ';
export const REWARD_POINTS = 'Reward points calculated:-';
export const ERROR_MESSAGE = 'An error occurred while fetching data. Please try again later.';
export const MONTHLY_REWARD = 'Monthly Reward points of';
export const TOTAL_POINTS = ' Total points of';
export const ASSIGNMENT = " = ";
export const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];